<header class="intro">
    <div class="intro-body">
        <div class="container-fluid">
            <div class="row">
                <div id="sequence" class="seq">
                    <div class="seq-screen">
                        <ul class="seq-canvas">
                            <?PHP SlideShows_Widget_Slideshow::getInstance()->setLan($this->lan)->setCat("RealState")->render(); ?>
                        </ul>
                    </div>

                    <ul rel="sequence" class="seq-pagination" role="navigation" aria-label="Pagination">
                        <?PHP SlideShows_Widget_Slideshow::getInstance()->setLan($this->lan)->setCat("RealState")->renderPag(); ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>


<section id="real-state" class="container content-section">
    <div class="row item-noticias active bg-white" rel="1">
        <div class="col-lg-12 text-center">
            <h3 class="color-2 text-left"><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleRealState')->TxtDescription; ?></h3>
        </div>

        <div class="col-lg-12">
            <p><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtRealState')->TxtDescription; ?></p>
        </div>
        <img class="img-responsive"
             src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/plano.jpg" alt=""/>

    </div>
</section>


<section id="gallery" class="container-fluid content-section text-center">
    <h2 class="text-red text-center color-5">Gallery</h2>
    <div class="row">
         <?PHP Gallery2_Widget_Gallery::getInstance()->setLan($this->lan)->setLimit(12)->render(); ?>
    </div>
</section>