<?PHP

$db = new Entities_Idiomas();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado de Idiomas";
$grid->setIdField("IdiId");
$grid->setQuery($db->getList());
$grid->setAlias(array("IdiNombre" => "Nombre", "IdiEscribe" => "Escribe", "IdiLee" => "Lee", "IdiHabla" => "Habla"));
$grid->setFilters(array("IdiNombre" => get('IdiNombre')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Idiomas/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Idiomas/Edit/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Idiomas/Delete/id/_ID_' . "':'';");

$grid->customField("IdiStatus", array("value" => array('1' => 'Leido', '0' => 'No Leido')));

$grid->render();
