<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Links";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Links");

$control = new Com_Wizard_Form_Control();
$control->name = "Nombre";
$control->label = "Nombre";
$control->default = $this->Nombre;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Apellido";
$control->label = "Apellido";
$control->default = $this->Apellido;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Sexo";
$control->label = "Sexo";
$control->default = $this->Sexo;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "EstadoCivil";
$control->label = "EstadoCivil";
$control->default = $this->EstadoCivil;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Nacimiento";
$control->label = "Nacimiento";
$control->default = $this->Nacimiento;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Pais";
$control->label = "Pais";
$control->default = $this->Pais;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Ciudad";
$control->label = "Ciudad";
$control->default = $this->Ciudad;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Direccion";
$control->label = "Direccion";
$control->default = $this->Direccion;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Telefono";
$control->label = "Telefono";
$control->default = $this->Telefono;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Celular";
$control->label = "Celular";
$control->default = $this->Celular;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Email";
$control->label = "Email";
$control->default = $this->Email;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Documento";
$control->label = "Documento de identidad";
$control->default = $this->Documento;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Numero";
$control->label = "Numero documento de identidad";
$control->default = $this->Numero;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Sib";
$control->label = "S.I.B";
$control->default = $this->Sib;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Leido');
$control->addItem('0', 'No Leido');
$form->add($control);

$form->render();
