<?PHP

$db = new Entities_Personas();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado de Personas";
$grid->setIdField("PerId");
$grid->setQuery($db->getList());
$grid->setAlias(array("PerNombre" => "Nombre", "PerApellido" => "Apellidos", "PerPais" => "Pais"));
$grid->setFilters(array("PerNombre" => get('PerNombre')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Personas/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Personas/Edit/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Personas/Delete/id/_ID_' . "':'';");

$grid->customField("PerStatus", array("value" => array('1' => 'Leido', '0' => 'No Leido')));

$grid->render();
