<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Sports";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Sports");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Sports/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);
    $form->addTab("Imagenes (" . $language->LanName . ")", Com_Helper_Url::getInstance()->urlBase . "/Admin/Sports/Images/lan/" . $language->LanId . "/id/" . get('id'), false);
}


$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Title";
$control->label = "Titulo";
$control->default = $this->Title;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Editor();
$control->name = "Description";
$control->label = "Description";
$control->default = $this->Description;
$control->required = true;
$control->rows = 5;
$control->addParameter("style ", "height:90px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Imagen";
$control->default = $this->Image;
$control->required = true;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Banner";
$control->label = "Banner";
$control->default = $this->Banner;
$control->required = false;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');
$form->add($control);

$form->render();
