<?PHP

$db = new Entities_Sport();
$grid = new Com_Wizard_Grid();
$grid->title = "Sport List";
$grid->setIdField("SpoId");
$grid->setLanField("SpoLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "SpoTitle" => "Titulo", "SpoStatus" => "Estado"));
$grid->setFilters(array("SpoTitle" => get('SpoTitle')));


$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Sports/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

//$grid->addAction("list-alt", "Linea de tiempo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Timelines/Index/lan/_LANGUAGE_/idPro/_ID_');
$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Sports/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Sports/Delete/id/_ID_' . "':'';");


$grid->customField("SpoStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));


$grid->render();
