<?PHP
$cadena = get("QUERY_STRING");
$idCliente = substr($cadena, strlen($cadena) - 1, strlen($cadena));
$pro = Projects_Model_Project::getInstance()->getByClient($idCliente, $this->lan);
echo ($pro);

?>

<section id="proyectos" class="cliente-proyecto container content-section text-center">

    <div class="row bg-cliente bg-white text-left">

        <?PHP
        Projects_Widget_Project::getInstance()->setLan($this->lan)->setLimit(6)->setClient($idCliente)->render();
        ?>
    </div>

</section>
<section id="mas-proyectos" class="container content-section text-center">
    <div class="row bg-white">
        <h2>Mas proyectos</h2>
    </div>
</section>

<section id="mas-proyectos-list" class="container content-section text-center">
    <div class="row bg-white">
        <div class="col-md-12">
            <ul class="col-md-12">
                <?PHP Projects_Widget_ProjectList::getInstance()->setLan($this->lan)->setLimit(6)->setClient($idCliente)->render(); ?>
            </ul>
        </div>
    </div>
</section>


