<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Links";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Software");

$control = new Com_Wizard_Form_Control();
$control->name = "Nombre";
$control->label = "Nombre";
$control->default = $this->Nombre;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Nivel";
$control->label = "Nivel";
$control->default = $this->Nivel;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "PerId";
$control->label = "PerId";
$control->default = $this->PerId;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Leido');
$control->addItem('0', 'No Leido');
$form->add($control);

$form->render();
