<div class="site-header">
    <div class="header-logo">

        <a href="http://www.muwom.com/" title="MUWOM">
            <img class="img-responsive"
                 src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/logo-hobesound.jpg"
                 alt="MUWOM">
        </a>

    </div>
    <div class="language-selector"><a class="lang_link lang_active" href="http://www.muwom.com/">es</a>/<a
            class="lang_link " href="http://www.muwom.com/en/">en</a></div>
    <div class="header-menu">
        <nav style="display: none">
            <ul id="menu-inneramenu" class="">
                <li class="menu-item menu-item-type-post_type menu-item-object-page"><a
                        href="http://www.muwom.com/nosotros/">Nosotros</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page"><a
                        href="http://www.muwom.com/servicios/">Servicios</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page"><a
                        href="http://www.muwom.com/proyectos/">Proyectos</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page"><a
                        href="http://www.muwom.com/proyectos-propios/">Proyectos propios</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page"><a
                        href="http://www.muwom.com/blog/">Blog</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page"><a
                        href="http://www.muwom.com/contacto/">Contacto</a></li>
            </ul>
            <div class="contact-social">
                <ul class="social-icons clearfix">
                    <li class="col-xs-4"><a href="https://twitter.com/muwom" target="_blank" title=""><i
                                class="fa fa-twitter"></i></a></li>
                    <li class="col-xs-4"><a href="https://www.facebook.com/muwom" target="_blank" title=""><i
                                class="fa fa-facebook"></i></a></li>
                    <li class="col-xs-4"><a href="https://www.instagram.com/muwom/" target="_blank" title=""><i
                                class="fa fa-instagram"></i></a></li>
                    <li class="col-xs-4"><a href="https://www.linkedin.com/company/muwom" target="_blank" title=""><i
                                class="fa fa-linkedin"></i></a></li>
                    <li class="col-xs-4"><a
                            href="https://play.spotify.com/user/1144799332/playlist/2aSag2sGoonAAMNgn7GHaO?play=true&amp;utm_source=open.spotify.com&amp;utm_medium=open"
                            target="_blank" title=""><i class="fa fa-spotify"></i></a></li>
                    <li class="col-xs-4"><a href="https://www.youtube.com/user/themuwom" target="_blank" title=""><i
                                class="fa fa-youtube"></i></a></li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="header-toggle">
        <i class="fa fa-bars"></i>
    </div>
</div>

<section id="news" class="container-fluid content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 container">
            <div class="row item-noticias active bg-white" rel="1">
                <div class="col-lg-12">
                    <h2> <?= strtoupper($this->article->NewTitle); ?></h2>
                </div>
                <div class="col-lg-12 p-image">
                    <img class="img-responsive"
                         src="<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->article->NewImage; ?>"/>
                </div>
                <div class="col-lg-12 p-content-2">
                    <div class="">

                        <div class="container-fluid autoridades-label text-center cocogose">
                            <span><?PHP echo $this->article->NewTitle; ?></span>
                        </div>
                        <br>

                        <div> <?PHP echo $this->article->NewContent; ?></div>

                        <div class="col-md-12 text-pink cocogose">
                            <h5>Autor: <?PHP echo $this->article->NewAuthor; ?></h5>
                            <h5>Fecha: <?PHP echo $this->article->NewDate; ?></h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12"><h2 class="text-pink cocogose"
                                           style="margin-top: 15px"><?PHP echo $this->translator->news; ?></h2></div>
            </div>
            <div class="row nav-news">
                <?PHP News_Widget_News::getInstance()->setLan($this->lan)->setLimit(3)->setCategory($this->article->NewCatId)->render(); ?>
            </div>
        </div>
    </div>
</section>
