<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Calendario";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Calendar");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Calendar/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "SpoId";
$control->label = "Sport";
$control->default = $this->SpoId;
$control->required = true;
foreach ($this->Sports as $type) {
    $control->addItem($type->SpoId, $type->SpoTitle);
}
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Event";
$control->label = "Event";
$control->default = $this->Event;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Description";
$control->label = "Descripcion";
$control->default = $this->Description;
$control->required = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_Date();
$control->name = "Date";
$control->label = "Date";
$control->default = $this->Date;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');

$form->add($control);

$form->render();
