<!DOCTYPE html>
<html lang="es">
<head>

    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Neblux - La manera más inteligente de usar el Transporte Público">
    <meta name="author" content="Neblux">
    <meta name="robots" content="index,follow">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Neblux - La manera más inteligente de usar el Transporte Público">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="theme-color" content="#db5945">
    <title><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titlePage')->TxtDescription; ?></title>

    <!-- Facebook -->
    <meta property="og:locale" content="en_GB">
    <meta property="og:url"
          content="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, 'page/' . $this->page->PagUrl); ?>">
    <meta property="og:title" content="<?PHP echo $this->page->PagName; ?>">
    <meta property="og:site_name" content="<?PHP echo $this->translator->pageTitle; ?>">
    <meta property="og:description" content="<?PHP echo $this->page->PagDescription; ?>">
    <meta property="og:image"
          content="<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->page->PagImage; ?>">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="80">
    <meta property="og:image:height" content="80">
    <meta property="og:type" content="website">

    <!-- Fav and Touch Icons -->
    <meta name="msapplication-TileColor" content="#d9534f">
    <meta name="msapplication-TileImage"
          content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/ms-icon-144x144.png">
    <meta name="msapplication-config"
          content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public//favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <link rel="apple-touch-icon" sizes="57x57"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png"
          sizes="32x32">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/android-192x192.png"
          sizes="192x192">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-96x96.png"
          sizes="96x96">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png"
          sizes="16x16">
    <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
    <link rel="shortcut icon"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
          type="image/x-icon"/>
    <!-- Google Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">


    <!-- Custom Fonts -->

    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
          type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">


    <?PHP
    Com_Helper_Style::getInstance()->addFile("Public/bootstrap.css")
        ->addFile("Public/hobesound.css")
        ->addFile("Public/font-awesome.min.css")
        ->addFile("Public/sequence-theme.basic.min.css")
        ->addFile("Public/jquery.flexisel.css")
        ->addFile("Public/slick.css")
        ->addFile("Public/slick-theme.css");
    echo Com_Helper_Style::getInstance();
    ?>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<nav class="navbar navbar-custom navbar-fixed-top hidden" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">
                <i class="fa fa-play-circle"></i> <span class="light">Start</span> Bootstrap
            </a>
        </div>

        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#download">Download</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<header class="intro">
    <div class="intro-body">
        <div class="container-fluid">
            <div class="row">
                <div id="sequence" class="seq">
                    <div class="seq-screen">
                        <ul class="seq-canvas">
                            <?PHP SlideShows_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>

                        </ul>
                    </div>

                    <ul rel="sequence" class="seq-pagination" role="navigation" aria-label="Pagination">
                        <?PHP SlideShows_Widget_Slideshow::getInstance()->setLan($this->lan)->renderPag(); ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>


<section id="real-state" class="container content-section">
    <div class="row item-noticias active bg-white" rel="1">
        <div class="col-lg-12 text-center">
            <h3 class="color-2 text-left"><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleAboutUs')->TxtDescription; ?></h3>
        </div>

        <div class="col-lg-12">
            <p><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtAboutUs')->TxtDescription; ?></p>
        </div>
        <img class="img-responsive" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/real-state-image.jpg" alt=""/>

    </div>
</section>


<section id="life-style" class="container content-section text-center">
    <div class="row">
        <h2>Life Style</h2>

        <div class="col-md-4  ls-shopping">
            <div class="ls-header">
                <img class="img-responsive"
                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/ic-shoping-2.jpg" alt=""/>

                <h2 class="text-red">Shopping</h2>
            </div>
            <ul class="fs-scroll">
                <li>
                    <a href="">item 1</a>
                </li>
                <li>
                    <a href="">item 2</a>
                </li>
                <li>
                    <a href="">item 3</a>
                </li>
                <li>
                    <a href="">item 4</a>
                </li>
                <li>
                    <a href="">item 5</a>
                </li>
                <li>
                    <a href="">item 6</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4  ls-beach">
            <div class="ls-header">
                <img class="img-responsive"
                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/ic-beach-2.jpg" alt=""/>

                <h2 class="text-red">Beach</h2>
            </div>
            <ul class="fs-scroll">
                <li>
                    <a href="">item 1</a>
                </li>
                <li>
                    <a href="">item 2</a>
                </li>
                <li>
                    <a href="">item 3</a>
                </li>
                <li>
                    <a href="">item 4</a>
                </li>
                <li>
                    <a href="">item 5</a>
                </li>
                <li>
                    <a href="">item 6</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 ls-restaurant">
            <div class="ls-header">
                <img class="img-responsive"
                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/ic-restaurant-2.jpg" alt=""/>

                <h2 class="text-red">Restaurants</h2>
            </div>
            <ul class="fs-scroll">
                <li>
                    <a href="">item 1</a>
                </li>
                <li>
                    <a href="">item 2</a>
                </li>
                <li>
                    <a href="">item 3</a>
                </li>
                <li>
                    <a href="">item 4</a>
                </li>
                <li>
                    <a href="">item 5</a>
                </li>
                <li>
                    <a href="">item 6</a>
                </li>
            </ul>
        </div>
    </div>
</section>

<section id="location" class="container-fluid content-section text-center">
    <div class="row">
        <h2 class="bg-color-3 color-5">Location</h2>

        <div id="map"></div>
    </div>
</section>

<section id="contact" class="container-fluid content-section text-center">
    <div class="row">
        <h2 class="bg-color-1 color-5">Location</h2>

        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-offset-1">
                    <h3 class="text-left color-1">titulo</h3>

                    <p>algo 1</p>

                    <p>algo 2</p>

                    <p>algo 3</p>

                    <p>algo 4</p>
                </div>
                <div class="col-md-4 col-md-offset-2">
                    <form>
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="password" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" id="detail" placeholder="Message" rows="4"></textarea>
                        </div>
                        <div class="form-group text-right">
                            <button type="submit" class="btn btn-hobesound-green">Submit</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<footer>
    <div class="container text-center">
        <p><a target="_blank" href="http://qwerty.com.bo/es/page/index.html?ref=hobesound"><img height="40"
                                                                                                src="http://localhost/bolpegas-web/Resources/Image/Public/logo-qwerty.png"
                                                                                                alt=""></a></p>

        <p>Copyright © QWERTY 2016</p>
    </div>
</footer>


</body>

<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
    window.jQuery || document.write('<script src="http://localhost/neblux/Resources/Script/Public/jquery.min.js"><\/script>')
</script>
<!-- Google Map -->
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&amp;sensor=false"></script>
<?php
Com_Helper_Script::getInstance()->addFile("Public/jquery.js")
    ->addFile("Public/bootstrap.min.js")
    ->addFile("Public/jquery.easing.min.js")
    ->addFile("Public/imagesloaded.pkgd.min.js")
    ->addFile("Public/sequence.min.js")
    ->addFile("Public/sequence-theme.basic.min.js")
    ->addFile("Public/jquery.flexisel.js")
    ->addFile("Public/slick.min.js")
    ->addFile("Public/hobesound.js");


echo Com_Helper_Script::getInstance();
?>
<script>

    </
    html >