<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Equipo";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Team/Index/lan/".$this->Language."/idCat/".get('idCat'));


$form->addTab("Idioma por Defecto (" . $this->languages[0]->LanName . ")", "", true);

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Nombre";
$control->default = $this->Name;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Position";
$control->label = "Cargo";
$control->default = $this->Position;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Description";
$control->label = "Descripcion";
$control->default = $this->Description;
$control->required = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Imagen";
$control->default = $this->Image;
$control->required = true;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Linkedin";
$control->label = "Linkedin";
$control->default = $this->Linkedin;
$control->length = 50;
$control->required = true;
$form->add($control);

$form->render();