<?PHP

$db = new Entities_Life();
$grid = new Com_Wizard_Grid();
$grid->title = "Life Style List";
$grid->setIdField("CerId");
$grid->setLanField("CerLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "CerName" => "Nombre", "CerStatus" => "Estado"));
$grid->setFilters(array("CerName" => get('CerName')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Life/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Life/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Life/Delete/id/_ID_' . "':'';");

$grid->customField("CerStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));
$grid->render();
